### ISSUE TITLE
requirements.txt不完善

### ISSUE THREAD

**Issue by yangxinyi-bigdata** [duolabmeng6/pyefun#54]
在使用模块功能过程中, 多次提示xxx模块未安装. 为何不将需要的依赖模块都在requirements.txt说明, 一次性安装完成呢?
具体示例:
/Users/mac/opt/anaconda3/bin/python3.8 /Users/mac/Downloads/00.code/pyefun/示例代码/testocr.py 
Traceback (most recent call last):
  File "/Users/mac/Downloads/00.code/pyefun/示例代码/testocr.py", line 2, in <module>
    from pyefun import *
  File "/Users/mac/Downloads/00.code/pyefun/pyefun/__init__.py", line 9, in <module>
    from pyefun.核心支持库.日期时间操作 import *
  File "/Users/mac/Downloads/00.code/pyefun/pyefun/核心支持库/日期时间操作.py", line 15, in <module>
    import pendulum
ModuleNotFoundError: No module named 'pendulum'

**Comment by duolabmeng6** [comment]
因为很卡 requirements.txt 你自己项目要什么就装什么把~这个pyefun里面很多包的中文库
